version: '3.8'
services:
  comfyui:
    image: ghcr.io/comfyanonymous/comfyui:latest
    ports:
      - "8188:8188"
    command: >
      python main.py
      --listen 0.0.0.0
      --port 8188
      --enable-cors-header
    volumes:
      - ./comfyui_data:/data
  proxy:
    image: python:3.10-slim
    ports:
      - "3002:3002"
    volumes:
      - ./proxy:/app
    working_dir: /app
    command: >
      sh -c "pip install flask flask‑cors requests &&
             python app.py"
